[package]
name = "playmusicrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arma-rs = "1.10.4"

[lib]
name = "playmusicrs"
crate-type = ["cdylib"]
