# build Golang app for Linux
FROM golang:1.21

WORKDIR /app

# get gcc-multilib, gcc-mingw-w64 and libasound2-dev
RUN apt update
RUN apt install -y gcc-multilib gcc-mingw-w64 libasound2-dev

CMD ["/bin/sh"]