[package]
name = "influxdb"
version = "1.0.0"
edition = "2021"

[dependencies]
arma-rs = "1.10.4"
influxc = "0.4.2"
openssl = { version = "0.10", features = ["vendored"] }

[lib]
name = "influxdb"
crate-type = ["cdylib"]
