# Linting configuration
# https://brettmayson.github.io/HEMTT/analysis/config.html
# https://brettmayson.github.io/HEMTT/analysis/sqf.html

[sqf.banned_commands]
options.banned = ["execVM"]
options.ignore = ["createSoundSource"]

[sqf.var_all_caps]
options.ignore = ["ACE_RECOMPILES", "ACE_PREP_RECOMPILE"]
