name = "rtf42"
prefix = "rtf42"
author = "42nd RTF Team"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_*.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_rtf42_ca.paa",
    "meta.cpp",
    "rtf42_main_menu.mp3",
    "ffmpeg.exe"
]

[hemtt.launch.default]
workshop = []
presets = [
    "main", # .html presets from .hemtt/presets/
]
dlc = []
optionals = []
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
    "D:\\Arma3Projects\\rtf42\\missions\\rtf42_base_test_mission.VR\\mission.sqm", # Launch into existing Editor Mission - \\ needed - Change what ever you path is
]
