name = "rtf42"
prefix = "rtf42"
author = "42nd RTF Team"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_*.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_rtf42_ca.paa",
    "meta.cpp",
    "rtf42_main_menu.mp3",
    "ffmpeg.exe"
]

[version]
git_hash = 0

[properties]
version = "v2024.1.0-rc.3"

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
]
