name = "rtf42"
prefix = "rtf42"
author = "42nd RTF Team"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_*.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_rtf42_ca.paa",
    "meta.cpp",
    "rtf42_main_menu.mp3",
]

[hemtt.launch.default]
workshop = ["2369477168"]
presets = [
    "rft42-mods", # .html presets from .hemtt/presets/
]
dlc = []
optionals = []
parameters = [
    "-skipIntro",        # These parameters are passed to the Arma 3 executable
    "-noSplash",         # They do not need to be added to your list
    "-showScriptErrors", # You can add additional parameters here
    "-debug",
    "-filePatching",
    "-world=empty",
    "-noPause",
    "-noPauseAudio",
    "-unit=232333",
    #"D:\\rtf-42nd\\missions\\rtf42_base_test_mission.VR\\mission.sqm", # Launch into existing Editor Mission - \\ needed - Change what ever you path is
]

[hemtt.launch.server]
workshop = []
presets = [
    "rft42-mods", # .html presets from .hemtt/presets/
]
dlc = []
optionals = []
parameters = [
    "-server",
    "-port=2302",
    "-loadMissionToMemory",
    "-autoInit",
    "-filePatching",
    "-cfg=D:\\rtf-42nd\\server\\basic.cfg",
    "-config=D:\\rtf-42nd\\server\\server.cfg",
]

[hemtt.launch.player]
workshop = []
presets = [
    "rft42-mods", # .html presets from .hemtt/presets/
]
dlc = []
optionals = []
parameters = [
    "-skipIntro",         # These parameters are passed to the Arma 3 executable
    "-noSplash",          # They do not need to be added to your list
    "-showScriptErrors",  # You can add additional parameters here
    "-debug",
    "-filePatching",
    "-world=empty",
    "-noPause",
    "-noPauseAudio",
    "-connect=127.0.0.1",
    "-port=2302",
    "-window",
]
