[package]
name = "rtf42"
version = "1.0.0"
edition = "2021"

[lib]
name = "rtf42"
crate-type = ["cdylib"]

[dependencies]
arma-rs = "1.10.4"
appwrite_openapi = "1.0.0"
serde_json = "1.0.114"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0.197"
