name: Build extensions
on:
  workflow_call:
jobs:
  extensions:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@v4
        - name: Setup Docker
          uses: docker/setup-buildx-action@v3
        - name: Setup Cross
          uses: clechasseur/rs-cargo@v2
          with:
            command: install
            args: cross --git https://github.com/cross-rs/cross
        - name: Build Rust Extensions
          run: |
                    cd extensions
                    for d in */ ; do
                        d=${d::-1}
                        echo "Building $d"
                        cd $d
                        cross build --target x86_64-pc-windows-gnu --release --features=fltk-bundled
                        cross build --target x86_64-unknown-linux-gnu --release --features=fltk-bundled
                        mv target/x86_64-pc-windows-gnu/release/*.dll ${{ github.workspace }}/${d}_x64.dll
                        mv target/x86_64-unknown-linux-gnu/release/*.so ${{ github.workspace }}/${d}_x64.so
                        cd ..
                    done
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: extensions
            path: |
              *.so
              *.dll
