# .github/workflows/check.yaml
name: Check Workflow
on:
  workflow_call:
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@master
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT check
          run: hemtt check
