name: CI

on:
    pull_request_target:

concurrency:
    group: "${{ github.actor }} - ${{github.ref}} - ci"
    cancel-in-progress: true

jobs:
    validate:
        uses: ./validate.yml
    lint:
        uses: ./lint.yml
    check:
        uses: ./check.yml

    hemtt:
        name: Build with HEMTT
        permissions: write-all
        runs-on: windows-latest
        needs: [validate, lint, check]
        steps:
            - uses: ./base.yml
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt build
            - name: Rename build folder
              run: mv .hemttout/build .hemttout/@rtf42
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rtf42-${{ github.sha }}
                  path: .hemttout/@*
