name: CI

on:
    pull_request_target:

concurrency:
    group: "${{ github.actor }} - ${{github.ref}} - ci"
    cancel-in-progress: true

jobs:
    validate:
        uses: ./.github/workflows/validate.yml
    lint:
        uses: ./.github/workflows/lint.yml
    check:
        uses: ./.github/workflows/check.yml
    extensions:
        name: Extensions
        uses: ./.github/workflows/buildExtensions.yml

    hemtt:
        name: Build with HEMTT
        permissions: write-all
        runs-on: windows-latest
        needs: [validate, lint, check, extensions]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ./.github/workflows/base
              with:
                CDN_URL: ${{ secrets.CDN_URL }}
                TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
                TOLGEE_URL: ${{ secrets.TOLGEE_URL }}
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt build
            - name: Rename build folder
              run: mv .hemttout\\build .hemttout\\@rtf42
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rtf42-${{ github.sha }}
                  path: .hemttout\\@*
