name: CI

on:
    pull_request_target:

concurrency:
    group: "${{ github.actor }} - ${{github.ref}} - ci"
    cancel-in-progress: true

jobs:
    validate:
        uses: /MultiTheFranky/rtf-42nd/tree/main/.github/workflows/jobs/validate.yml@main
    lint:
        uses: /MultiTheFranky/rtf-42nd/tree/main/.github/workflows/jobs/lint.yml@main
    check:
        uses: /MultiTheFranky/rtf-42nd/tree/main/.github/workflows/jobs/check.yml@main

    hemtt:
        name: Build with HEMTT
        permissions: write-all
        runs-on: windows-latest
        needs: [validate, lint, check]
        steps:
            - uses: /MultiTheFranky/rtf-42nd/tree/main/.github/workflows/jobs/base.yml@main
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt build
            - name: Rename build folder
              run: mv .hemttout/build .hemttout/@rtf42
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rtf42-${{ github.sha }}
                  path: .hemttout/@*
