name: CI

on:
    push:
        branches:
            - main
    pull_request_target:

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@master
            - name: Validate SQF
              run: python3 tools/sqf_validator.py
            - name: Validate Config
              run: python3 tools/config_style_checker.py
            - name: Check for BOM
              uses: arma-actions/bom-check@master
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@master
            - name: Lint (sqflint)
              uses: arma-actions/sqflint@master
              continue-on-error: true # No failure due to many false-positives
    hemtt:
        name: Build with HEMTT
        runs-on: ubuntu-latest
        needs: [validate, lint]
        steps:
            - name: Checkout repo PR
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Setup GCC
              uses: egor-tensin/setup-gcc@v1
              with:
                version: latest
                platform: x64
            - name: Setup GO
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21.5
            - name: Build Extensions
              run: |
                  cd extensions
                  for d in */ ; do
                      cd $d
                      GOOS=linux GOARCH=386 go build -o ../../$d".so" -buildmode=c-shared index.go
                      GOOS=windows GOARCH=386 go build -o ../../$d".dll" -buildmode=c-shared index.go
                      # Build 64bit
                      GOOS=linux GOARCH=amd64 go build -o ../../$d"_x64.so" -buildmode=c-shared index.go
                      GOOS=windows GOARCH=amd64 go build -o ../../$d"_x64.dll" -buildmode=c-shared index.go
                      cd ..
                  done
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install translator
              run: cd extras/translator && npm install
            - name: Fill .env file with secrets
              run: echo -e "TOLGEE_API_KEY=${{ secrets.TOLGEE_API_KEY }}\nTOLGEE_URL=${{ secrets.TOLGEE_URL }}" >> extras/translator/.env
            - name: Run translator
              run: cd extras/translator && npm start
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt build
            - name: Rename build folder
              run: mv .hemttout/build .hemttout/@rtf42
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: rtf42-${{ github.sha }}
                  path: .hemttout/@*
