name: Lint Workflow
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@master
        - name: Lint (sqflint)
          uses: arma-actions/sqflint@master
          continue-on-error: true
