name: "Main Workflow"

permissions:
    contents: write

on:
    push:
        branches:
            - "main"

concurrency:
    group: "${{ github.actor }} - ${{github.ref}} - main"
    cancel-in-progress: true

jobs:
    validate:
        name: Validate
        uses: ./.github/workflows/validate.yml
    lint:
        name: Lint
        uses: ./.github/workflows/lint.yml
    check:
        name: Check
        uses: ./.github/workflows/check.yml
    extensions:
        name: Extensions
        uses: ./.github/workflows/buildExtensions.yml

    release:
        name: BETA Release
        permissions: write-all
        if: github.actor != 'kodiakhq[bot]'
        runs-on: windows-latest
        needs: [validate, lint, check, extensions]
        steps:
              - name: Checkout
                uses: actions/checkout@v4
              - uses: ./.github/workflows/base
                with:
                    CDN_URL: ${{ secrets.CDN_URL }}
                    TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
                    TOLGEE_URL: ${{ secrets.TOLGEE_URL }}
              - name: Retrieve base artifact
                uses: actions/download-artifact@v4
                with:
                  name: extensions
              - name: Execute version generator
                run: |
                    cd ${{ github.workspace }}\\tools\\version_generator
                    npm install
                    $VERSION=$(node index.js --beta)
                    echo "VERSION=$VERSION" >> $GITHUB_ENV
              - name: Setup HEMTT
                uses: arma-actions/hemtt@v1
              - name: Run HEMTT release
                run: hemtt release
              - name: Rename build folder
                run: mv ${{ github.workspace }}\\releases\\rtf42-latest.zip ${{ github.workspace }}\\releases\\@rtf42-${{env.VERSION}}.zip
              - name: Upload Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: rtf42-${{ env.VERSION }}
                    path: ${{ github.workspace }}\\releases\\@rtf42-${{env.VERSION}}.zip
              - uses: "marvinpinto/action-automatic-releases@latest"
                id: "automatic_releases"
                with:
                    repo_token: "${{ secrets.PAT }}"
                    automatic_release_tag: "${{ env.VERSION }}"
                    prerelease: true
                    title: "Release ${{ env.VERSION }}"
              - name: Upload asset
                uses: shogo82148/actions-upload-release-asset@v1
                with:
                    upload_url: ${{ steps.automatic_releases.outputs.upload_url }}
                    asset_path: ${{ github.workspace }}\\releases\\@rtf42-${{env.VERSION}}.zip
                    asset_content_type: application/zip
                continue-on-error: true
              - name: PR to merge version to main branch
                uses: peter-evans/create-pull-request@v5
                with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "Update version to ${{ env.VERSION }}"
                  title: "Update version to ${{ env.VERSION }}"
                  body: "Update version to ${{ env.VERSION }}"
                  branch: "version-${{ env.VERSION }}"
                  base: "main"
                  branch-suffix: random
                  delete-branch: true
                  labels: |
                      automerge
                      automated pr
