# Workflow to run every hour to update the translation files
name: Update translations

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install translator
              run: cd tools/translator && npm install
            - name: Fill .env file with secrets
              run: echo -e "TOLGEE_API_KEY=${{ secrets.TOLGEE_API_KEY }}\nTOLGEE_URL=${{ secrets.TOLGEE_URL }}" >> tools/translator/.env
            - name: Run translator
              run: cd tools/translator && npm start
            - name: Check if there is an already PR
              id: check_pr
              run: |
                  if gh pr list --state open --base translations | grep -q "No open pull requests found"; then
                      echo "::set-output name=pr_number::"
                  else
                      gh pr list --state open --base translations | grep -oP '(?<=#)\d+' | head -n 1
                  fi
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Pull Request
              id: cpr
              if: steps.check_pr.outputs.pr_number == ''
              uses: peter-evans/create-pull-request@v5
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: Update translations files
                committer: GitHub <noreply@github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                branch: translations
                delete-branch: true
                title: '[Translations] Update translations files'
                body: |
                  Update translations files
                  - Auto-generated by [create-pull-request][1]

                  [1]: https://github.com/peter-evans/create-pull-request
                labels: |
                    translations
                    automerge
                    automated pr
                draft: false
            - name: Commit the changes
              if: steps.check_pr.outputs.pr_number != ''
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                  git checkout translations
                  git add .
                  git commit -m "Update translations files"
                  git push
            - name: Add label automerge to the PR
              if: steps.check_pr.outputs.pr_number != ''
              run: gh pr edit ${{ steps.check_pr.outputs.pr_number }} --add-label automerge
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
