# Workflow to run every hour to update the translation files
name: Update translations

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install translator
              run: cd extras/translator && npm install
            - name: Fill .env file with secrets
              run: echo -e "TOLGEE_API_KEY=${{ secrets.TOLGEE_API_KEY }}\nTOLGEE_URL=${{ secrets.TOLGEE_URL }}" >> extras/translator/.env
            - name: Run translator
              run: cd extras/translator && npm start
            - name: Merge changes
              run: |
                  git config --global user.name "tolgee-bot"
                  git config --global user.email "noreply@multithefranky.com"
                  git add .
                  if [[ -z $(git status -s) ]]; then exit 0; fi
                  git commit -m "Translations updated"
                  git push
