# .github/workflows/validate.yaml
name: Validate Workflow
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@master
        - name: Validate SQF
          run: python3 tools/sqf_validator.py
        - name: Validate Config
          run: python3 tools/config_style_checker.py
        - name: Check for BOM
          uses: arma-actions/bom-check@master
